spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ese15
    username: root
    password: 1234567
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create
  jackson:
    serialization:
      fail-on-empty-beans: false
  application:
    name: ese15

